#!/usr/bin/env bash

# Used before setting up a fresh install of macOS
# Accumulates all machine specific files that are not under VCS into a single directory

set -e

p_header()  { printf "\\n\\033[1;97m%s\\033[0m\\n" "$@"; }
p_success() { printf "\\033[1;32m❯\\033[0m %s\\n" "$@"; }
p_error()   { printf "\\033[1;31m❯\\033[0m %s\\n" "$@"; }
p_warn()   { printf "\\033[1;33m❯\\033[0m %s\\n" "$@"; }

# Create the backup dir
BACKUP_DIR="$HOME/backup-$(date +%Y-%m-%d)"
mkdir -p "$BACKUP_DIR"

# Backup crontab
p_header 'crontab'
if crontab -l > "$BACKUP_DIR/crontab"; then
  p_success 'Backed up crontab'
else
  p_error 'Error backing up!'
fi

# Backup Applications directory list
p_header '/Applications'
if ls /Applications > "$BACKUP_DIR/applications.txt"; then
  p_success 'Backed up Applications directory list'
else
  p_error 'Error backing up!'
fi

# Backup /etc/hosts file
p_header '/etc/hosts'
if cp /etc/hosts "$BACKUP_DIR/hosts"; then
  p_success 'Backed up /etc/hosts'
else
  p_error 'Error backing up!'
fi

# Backup vim spellfile
p_header 'vim spellfile'
if cp "$HOME/.vim/spell/en.utf-8.add" "$BACKUP_DIR/en.utf-8.add"; then
  p_success 'Backed up vim spellfile'
else
  p_error 'Error backing up!'
fi

# Backup ~/.ssh
p_header "$HOME/.ssh"
if cp -R "$HOME/.ssh/" "$BACKUP_DIR/ssh"; then
  p_success 'Backed up ~/.ssh'
else
  p_error 'Error backing up!'
fi

# Backup ~/.aws
p_header "$HOME/.aws"
if cp -R "$HOME/.aws/" "$BACKUP_DIR/aws"; then
  p_success 'Backed up ~/.aws'
else
  p_error 'Error backing up!'
fi

# Backup ~/.getmail
p_header "$HOME/.getmail"
if cp -R "$HOME/.getmail/" "$BACKUP_DIR/getmail"; then
  p_success 'Backed up ~/.getmail'
else
  p_error 'Error backing up!'
fi

# Backup ~/.local/bin
p_header "$HOME/.local/bin"
if cp -R "$HOME/.local/bin/" "$BACKUP_DIR/local-bin"; then
  p_success 'Backed up ~/.local/bin'
else
  p_error 'Error backing up!'
fi

# Backup zsh_history
p_header "$HOME/.zsh_history"
if cp "$HOME/.zsh_history" "$BACKUP_DIR/zsh_history"; then
  p_success 'Backed up zsh_history'
else
  p_error 'Error backing up!'
fi

# Backup zshrc.local
p_header "$HOME/.zshrc.local"
if cp "$HOME/.zshrc.local" "$BACKUP_DIR/zshrc.local"; then
  p_success 'Backed up zshrc.local'
else
  p_error 'Error backing up!'
fi

# Backup gitconfig.local
p_header "$HOME/.gitconfig.local"
if cp "$HOME/.gitconfig.local" "$BACKUP_DIR/gitconfig.local"; then
  p_success 'Backed up gitconfig.local'
else
  p_error 'Error backing up!'
fi

# Backup fonts
p_header "$HOME/Library/Fonts"
if cp -R "$HOME/Library/Fonts/" "$BACKUP_DIR/Fonts"; then
  p_success 'Backed up ~/Library/Fonts'
else
  p_error 'Error backing up!'
fi

# Backup Visual Studio Code settings
p_header "Visual Studio Code settings"
if cp -R "$HOME/Library/Application Support/Code/User" "$BACKUP_DIR/visual-studio-code"; then
  p_success 'Backed up Visual Studio Code settings'
else
  p_error 'Error backing up!'
fi
