cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'aspell'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'composer'
brew 'coreutils'
brew 'ctags'
brew 'diff-so-fancy'
brew 'exiftool'
brew 'fasd'
brew 'fd'
brew 'ffmpeg', args: ['with-libvpx', 'with-x265', 'with-fdk-aac']
brew 'getmail'
brew 'gifsicle'
brew 'git', args: ['with-pcre2']
brew 'gnu-sed', args: ['with-default-names']
brew 'htop-osx'
brew 'httpie'
brew 'imagemagick@6'
brew 'jq'
brew 'macvim'
brew 'media-info'
brew 'neovim'
brew 'nvm'
brew 'openssl'
brew 'pandoc'
brew 'php'
brew 'pipenv'
brew 'pstree'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby-build'
brew 'shellcheck'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-override-system-vi', 'without-python']
brew 'wget'
brew 'yarn', args: ['without-node']
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'arq'
cask 'backblaze'
cask 'bettertouchtool'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'iina'
cask 'istat-menus'
cask 'joinme'
cask 'kitty'
cask 'sequel-pro'
cask 'sip'
cask 'sizeup'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'ubersicht'
cask 'virtualbox'
cask 'visual-studio-code'
