#!/usr/bin/env bash

# Runs any additional scripts after doing a complete ./run
# Used to stop problematic roles from hanging up or erroring during ./run

set -e

echo
echo '> Running post-run script'

/usr/local/bin/brew cask install karabiner-elements
/usr/local/bin/brew cask install virtualbox

echo
