"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = '[▶▶](bright-black) '
format = """
$directory\
${custom.host_context}\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$line_break\
$jobs\
${custom.shlvl}\
$character
"""

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'

[custom.host_context]
command = """
[[ -n "${TMUX+set}" ]] && print -P "%m@$(tmux display-message -p '#S')"
"""
description = 'Displays hostname and tmux session only on dev hosts'
when = """ [[ $(hostname -s) =~ ^iffyarch ]] """
style = 'fg:#6c7086'

[custom.shlvl]
command = """
lvl=$(($SHLVL - 1))
[[ -n "${TMUX+set}" ]] && lvl=$(($lvl - 1))
(( lvl > 1 )) && echo "(+$(($lvl - 1)))"
"""
description = 'Displays SHLVL while taking into account tmux'
when = "true"
style = 'fg:black'

[cmd_duration]
format = ' [$duration]($style)'

[directory]
truncation_length = 2
truncate_to_repo = false
style = 'bold blue'

[directory.substitutions]
'~/' = ''

[fill]
symbol = '·'

[git_branch]
format = '[•](fg:#9399B2) [$symbol$branch(:$remote_branch)]($style) '
style = 'bold white'
symbol = ''

[git_status]
style = 'red'

[jobs]
symbol = '◆'
style = 'bold yellow'
