# vim:fileencoding=utf-8:ft=conf

# Based on the output of `brew bundle dump` (which must be run outside of tmux)

cask_args appdir: '/Applications'

# Taps
tap 'caskroom/cask'
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask-versions'

# GNU programs non-existing in macOS
brew 'watch'
brew 'wget'

# GNU programs whose BSD counterpart is installed in macOS
brew 'binutils'
brew 'coreutils'
brew 'diffutils'
brew 'findutils', args: ['with-default-names']
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'grep', args: ['with-default-names']
brew 'gzip'

# GNU programs existing in macOS which are outdated
brew 'bash'
brew 'less'
brew 'make', args: ['with-default-names']

# Custom programs
brew 'aspell'
brew 'awscli'
brew 'bat'
brew 'composer'
brew 'ctags'
brew 'diff-so-fancy'
brew 'exiftool'
brew 'fasd'
brew 'fd'
brew 'ffmpeg', args: ['with-libvpx', 'with-x265', 'with-fdk-aac']
brew 'fzf'
brew 'getmail'
brew 'gifsicle'
brew 'git', args: ['with-pcre2']
brew 'htop-osx'
brew 'httpie'
brew 'imagemagick@6'
brew 'jq'
brew 'macvim'
brew 'media-info'
brew 'neovim'
brew 'nvm'
brew 'openssl'
brew 'pandoc'
brew 'php'
brew 'pipenv'
brew 'pstree'
brew 'python@2'
brew 'python'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby-build'
brew 'shellcheck'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'teensy_loader_cli', args: ['with-libusb-compat']
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-override-system-vi', 'without-python']
brew 'yarn', args: ['without-node']
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'arq'
cask 'bettertouchtool'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'google-chrome'
cask 'iina'
cask 'istat-menus'
cask 'joinme'
cask 'kitty'
cask 'marked'
cask 'sequel-pro'
cask 'sip'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'ubersicht'
cask 'vagrant'
cask 'visual-studio-code'
