#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$CONFIG_DIR/ui.sh"

export ITEM_DIR="$CONFIG_DIR/items"
export PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
  blur_radius=50
  color="$BAR_COLOR"
  corner_radius=0
  display=main
  height=28
  margin=0
  padding_left=0
  padding_right=10
  position=bottom
  topmost=window
  y_offset=0
)
sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  icon.font="$NERD_FONT"
  label.font="$TEXT_FONT"
  label.color="$LABEL_COLOR"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  background.padding_right="$PADDINGS"
  background.padding_left="$PADDINGS"
)
sketchybar --default "${default[@]}"

# Left
source "$ITEM_DIR/windows.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/audio_output.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/slack.sh"

sketchybar --update
