#!/usr/bin/env osascript -l JavaScript

function getUnreadMailCount() {
  if (Application('Mail').running()) {
    return Application('Mail').inbox.unreadCount()
  }
  else {
    return '-'
  }
}

getUnreadMailCount()
