#!/bin/sh

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

brew update
brew upgrade

# Install homebrew packages
brew install ansible
brew install aspell
brew install bash
brew install cmake
brew install coreutils
brew install ctags
brew install diff-so-fancy
brew install exiftool
brew install fasd
brew install ffmpeg --with-faac
brew install getmail
brew install gifsicle
brew install git
brew install htop-osx
brew install httpie
brew install imagemagick --with-webp
brew install jq
brew install lame
brew install media-info
brew install neovim
brew install nvm
brew install pandoc
brew install python
brew install python3
brew install rbenv
brew install reattach-to-user-namespace
brew install ripgrep
brew install ruby-build
brew install shellcheck
brew install ssh-copy-id
brew install terminal-notifier
brew install the_silver_searcher
brew install tmux
brew install tree
brew install vim --with-override-system-vi --without-python
brew install wget
brew install youtube-dl
brew install zsh
brew install zsh-autosuggestions
brew install zsh-completions
brew install zsh-syntax-highlighting

brew cleanup
