#!/bin/sh

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

brew update
brew upgrade

# Install homebrew packages
brew install git
brew install zsh
brew install rbenv
brew install ruby-build
brew install wget
brew install tmux
brew install reattach-to-user-namespace
brew install tree
brew install htop-osx
brew install ack
brew install z
brew install macvim --override-system-vim

brew cleanup
