#!/bin/sh

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

brew update
brew upgrade

# Install homebrew packages
brew install git
brew install zsh
brew install bash
brew install rbenv
brew install ruby-build
brew install wget
brew install tmux
brew install reattach-to-user-namespace
brew install tree
brew install htop-osx
brew install ack
brew install z
brew install python
brew install vim --override-system-vi
brew install the_silver_searcher
brew install terminal-notifier
brew install getmail
brew install yuicompressor

brew cleanup
