#!/bin/sh
# Setup a machine for Sublime Text 3
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime3/User" "$sublime_dir"

# get tomorrow night theme
cd "$sublime_dir"
git clone https://github.com/chriskempson/tomorrow-theme.git "Theme - Tomorrow"

ln -s "/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
