#!/bin/bash
#
# installs dotfiles to $HOME dir

set -e

# set $DOTFILES in env or use default
DOTHOME=${DOTFILES:-"$HOME/.dotfiles"}

SIMPLE_FILES=(
  'bash_profile'
  'vim'
  'vimrc'
)

EXTRA_FILES=(
  'ackrc'
  'agignore'
  'gemrc'
  'gitconfig'
  'rspec'
  'tmux.conf'
  'zshrc'
)

FILES=( "${SIMPLE_FILES[@]}" "${EXTRA_FILES[@]}" )

while getopts ":s" opt; do
  case $opt in
    s)
      FILES=( "${SIMPLE_FILES[@]}" )
      ;;
  esac
done

e_header()  { printf "\n\033[1;36m$@\033[0m\n"; }
e_success() { printf " \033[1;32m✔\033[0m  $@\n"; }
e_error()   { printf " \033[1;31m✖\033[0m  $@\n"; }
e_arrow()   { printf " \033[1;33m➜\033[0m  $@\n"; }

install() {
  e_header 'Installing dotfiles...'

  for file in "${FILES[@]}"; do
    source="$DOTHOME/$file"
    dest="$HOME/.$file"

    # skip if link is the same
    if test "$source" -ef "$dest"; then
      e_success "Already linked: $file"
      continue
    fi

    # backup file if it exists.
    if [[ -e "$dest" ]]; then
      e_arrow "Backing up $HOME/.$file"
      mv "$dest" "$dest.backup"
    fi

    ln -sfF "$source" "$dest"
    e_success "Linked: $file"
  done

  e_header "All done!"
  echo
}

install
