#!/bin/bash
#
# installs dotfiles to $HOME dir

set -e

# set DOTFILES in env or use default
dotdir=${DOTFILES:-"$HOME/.dotfiles"}

# basic set of dotfiles (useful for remote machines)
basic_files=(
  'bash_profile'
  'vim'
  'vimrc'
)

# extra set of dotfiles (personal machine)
extra_files=(
  'ackrc'
  'agignore'
  'ctags'
  'gemrc'
  'gitconfig'
  'gitignore_global'
  'git_template'
  'rspec'
  'tmux.conf'
  'zshrc'
)

files=( "${basic_files[@]}" "${extra_files[@]}" )

while getopts ":s" opt; do
  case $opt in
    s)
      files=( "${basic_files[@]}" )
      ;;
  esac
done

e_header()  { printf "\n\033[1;36m$@\033[0m\n"; }
e_success() { printf " \033[1;32m✔\033[0m  $@\n"; }
e_error()   { printf " \033[1;31m✖\033[0m  $@\n"; }
e_arrow()   { printf " \033[1;33m➜\033[0m  $@\n"; }

install() {
  e_header 'Installing dotfiles...'

  for file in "${files[@]}"; do
    local source="$dotdir/$file"
    local dest="$HOME/.$file"

    # skip if link is the same
    if [[ "$source" -ef "$dest" ]]; then
      e_success "Already linked: $file"
      continue
    fi

    # backup file if it exists.
    if [[ -e "$dest" ]]; then
      e_arrow "Backing up $HOME/.$file"
      mv "$dest" "$dest.backup"
    fi

    ln -sfF "$source" "$dest"
    e_success "Linked: $file"
  done

  e_header "All done!"
  echo
}

install
