#!/bin/bash
#
# installs a simplified set of dotfiles to $HOME dir

set -e

# set in zshrc
DOTHOME=${DOTFILES:-"$HOME/.dotfiles"}

FILES=(
  'ackrc'
  'agignore'
  'bash_profile'
  'gemrc'
  'gitignore_global'
  'rspec'
  'vim'
  'vimrc'
)

e_header()  { echo -e "\n\033[1;36m$@\033[0m"; }
e_success() { echo -e " \033[1;32m✔\033[0m  $@"; }
e_error()   { echo -e " \033[1;31m✖\033[0m  $@"; }
e_arrow()   { echo -e " \033[1;33m➜\033[0m  $@"; }

install() {
  e_header 'Installing dotfiles...'

  for file in "${FILES[@]}"; do
    source="$DOTFILES/$file"
    dest="$HOME/.$file"

    # skip if link is the same
    if test "$file" -ef "$dest"; then
      e_success "Already linked: $file"
      continue
    fi

    # backup file if it exists.
    if [[ -e "$dest" ]]; then
      e_arrow "Backing up $HOME/.$file"
      mv "$dest" "$dest.backup"
    fi

    ln -sf "$source" "$dest"
    e_success "Linked: $file"
  done

  e_header "All done!"
	echo
}

install
