" Name:         bti
" Description:  Dark monochromatic colorscheme
" Author:       Brandon Iffert <brandoniffert@gmail.com>
" Maintainer:   Brandon Iffert <brandoniffert@gmail.com>
" Website:      https://brandoniffert.com
" License:      Public domain
" Last Updated: Fri Jan 10 14:01:29 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'bti'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#3b4252', '#bf616a', '#a3be8c', '#ebcb8b',
        \ '#81a1c1', '#b48ead', '#88c0d0', '#e5e9f0', '#4c566a', '#bf616a',
        \ '#a3be8c', '#ebcb8b', '#81a1c1', '#b48ead', '#88c0d0', '#e5e9f0']
  if has('nvim')
    let g:terminal_color_0 = '#3b4252'
    let g:terminal_color_1 = '#bf616a'
    let g:terminal_color_2 = '#a3be8c'
    let g:terminal_color_3 = '#ebcb8b'
    let g:terminal_color_4 = '#81a1c1'
    let g:terminal_color_5 = '#b48ead'
    let g:terminal_color_6 = '#88c0d0'
    let g:terminal_color_7 = '#e5e9f0'
    let g:terminal_color_8 = '#4c566a'
    let g:terminal_color_9 = '#bf616a'
    let g:terminal_color_10 = '#a3be8c'
    let g:terminal_color_11 = '#ebcb8b'
    let g:terminal_color_12 = '#81a1c1'
    let g:terminal_color_13 = '#b48ead'
    let g:terminal_color_14 = '#88c0d0'
    let g:terminal_color_15 = '#e5e9f0'
  endif
  hi ColorColumn guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#242932 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#131520 guibg=#a3be8c guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#131520 guibg=#ebcb8b guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#131520 guibg=#bf616a guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#131520 guibg=#81a1c1 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#242932 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi iCursor guifg=#242932 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#242932 guibg=#ebcb8b guisp=NONE gui=bold cterm=bold
  hi LineNr guifg=#363d4a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#242932 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#4c566a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#242932 guibg=#e5e9f0 guisp=NONE gui=bold cterm=bold
  hi PmenuThumb guifg=#242932 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#bf616a guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SignColumn guifg=#131520 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#bf616a guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi SpellCap guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellLocal guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellRare guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#616e88 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#4c566a guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#4c566a guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#616e88 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#131520 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#363d4a guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=#131520 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#3b4252 guibg=#ebcb8b guisp=NONE gui=bold cterm=bold
  hi Underlined guifg=#e5e9f0 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi healthError guifg=#bf616a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi healthSuccess guifg=#a3be8c guibg=NONE guisp=NONE gui=bold cterm=bold
  hi healthWarning guifg=#ebcb8b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Boolean guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#616e88 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#e5e9f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Constant guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Debug guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#e5e9f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Identifier guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#e5e9f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Label guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e5e9f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Repeat guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#616e88 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Statement guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#c3d5b4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CursorLineNr LineNr
  hi! link diffAdded DiffAdd
  hi! link diffChanged DiffChange
  hi! link diffRemoved DiffDelete
  hi! link lCursor Cursor
  hi! link Macro Define
  hi! link Precondit PreProc
  hi! link WildMenu PmenuSel
  hi! link htmlEndTag htmlTag
  hi! link htmlItalic htmlItalic
  hi! link htmlH1 markdownH1
  hi! link htmlH2 markdownH1
  hi! link htmlH3 markdownH1
  hi! link htmlH4 markdownH1
  hi! link htmlH5 markdownH1
  hi! link htmlH6 markdownH1
  hi! link htmlSpecialChar SpecialChar
  hi! link htmlTag Keyword
  hi! link htmlTagN htmlTag
  hi! link jsBrackets Delimiter
  hi! link jsFuncCall Function
  hi! link jsFuncParens Delimiter
  hi! link jsThis Keyword
  hi! link jsPrototype Keyword
  hi! link jsRegexpString SpecialChar
  hi! link jsObjectKey jsonKeyword
  hi markdownH1 guifg=#e5e9f0 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi! link markdownBold Bold
  hi! link markdownBoldDelimiter Keyword
  hi! link markdownFootnoteDefinition markdownFootnote
  hi! link markdownH2 markdownH1
  hi! link markdownH3 markdownH1
  hi! link markdownH4 markdownH1
  hi! link markdownH5 markdownH1
  hi! link markdownH6 markdownH1
  hi! link markdownIdDelimiter Keyword
  hi! link markdownItalic Italic
  hi! link markdownItalicDelimiter Keyword
  hi! link markdownLinkDelimiter Keyword
  hi! link markdownLinkTextDelimiter Keyword
  hi! link markdownListMarker Keyword
  hi! link markdownRule Keyword
  hi! link markdownHeadingDelimiter Keyword
  hi! link sassAmpersand Keyword
  hi! link sassControl Keyword
  hi! link sassControlLine Keyword
  hi! link sassExtend Keyword
  hi! link sassFor Keyword
  hi! link sassFunctionDecl Keyword
  hi! link sassReturn Keyword
  hi! link vimFunc Function
  hi! link vimFunction Function
  hi! link vimUserFunc Function
  hi! link yamlBool Keyword
  hi! link yamlDocumentStart Keyword
  hi ALEError guifg=#bf616a guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEErrorSign guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=#ebcb8b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEWarningSign guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Keyword
  hi! link NERDTreeHelp Comment
  hi plugDeleted guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi QuickScopePrimary guifg=#bf616a guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi QuickScopeSecondary guifg=#bf616a guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi TermCursorNC guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi ColorColumn ctermfg=254 ctermbg=233 cterm=NONE
  hi Cursor ctermfg=235 ctermbg=254 cterm=NONE
  hi CursorColumn ctermfg=254 ctermbg=233 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=233 ctermbg=108 cterm=NONE
  hi DiffChange ctermfg=233 ctermbg=222 cterm=NONE
  hi DiffDelete ctermfg=233 ctermbg=131 cterm=NONE
  hi DiffText ctermfg=233 ctermbg=110 cterm=NONE
  hi Directory ctermfg=254 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=235 ctermbg=NONE cterm=NONE
  hi Error ctermfg=131 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=131 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=254 ctermbg=233 cterm=NONE
  hi Folded ctermfg=254 ctermbg=233 cterm=NONE
  hi iCursor ctermfg=235 ctermbg=254 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=222 cterm=bold
  hi LineNr ctermfg=237 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=235 ctermbg=254 cterm=NONE
  hi ModeMsg ctermfg=254 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=254 ctermbg=NONE cterm=NONE
  hi Normal ctermfg=254 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=240 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=254 ctermbg=233 cterm=NONE
  hi PmenuSbar ctermfg=254 ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=235 ctermbg=254 cterm=bold
  hi PmenuThumb ctermfg=235 ctermbg=254 cterm=NONE
  hi Question ctermfg=254 ctermbg=NONE cterm=NONE
  hi Search ctermfg=131 ctermbg=NONE cterm=underline
  hi SignColumn ctermfg=233 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=254 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=131 ctermbg=NONE cterm=bold,underline
  hi SpellCap ctermfg=131 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=131 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=131 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=60 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=240 ctermbg=233 cterm=NONE
  hi TabLine ctermfg=240 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=233 cterm=NONE
  hi TabLineSel ctermfg=254 ctermbg=233 cterm=NONE
  hi Terminal ctermfg=254 ctermbg=NONE cterm=NONE
  hi Title ctermfg=60 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=237 cterm=NONE
  hi VisualNOS ctermfg=233 ctermbg=254 cterm=NONE
  hi WarningMsg ctermfg=238 ctermbg=222 cterm=bold
  hi Underlined ctermfg=254 ctermbg=NONE cterm=underline
  hi healthError ctermfg=131 ctermbg=NONE cterm=bold
  hi healthSuccess ctermfg=108 ctermbg=NONE cterm=bold
  hi healthWarning ctermfg=222 ctermbg=NONE cterm=bold
  hi Boolean ctermfg=254 ctermbg=NONE cterm=NONE
  hi Character ctermfg=254 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=60 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=254 ctermbg=NONE cterm=bold
  hi Constant ctermfg=254 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=254 ctermbg=NONE cterm=NONE
  hi Define ctermfg=254 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=254 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=254 ctermbg=NONE cterm=NONE
  hi Float ctermfg=254 ctermbg=NONE cterm=NONE
  hi Function ctermfg=254 ctermbg=NONE cterm=bold
  hi Identifier ctermfg=254 ctermbg=NONE cterm=NONE
  hi Include ctermfg=254 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=254 ctermbg=NONE cterm=bold
  hi Label ctermfg=254 ctermbg=NONE cterm=NONE
  hi Number ctermfg=254 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=254 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=254 ctermbg=NONE cterm=bold
  hi Repeat ctermfg=254 ctermbg=NONE cterm=NONE
  hi Special ctermfg=254 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=254 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=60 ctermbg=NONE cterm=italic
  hi Statement ctermfg=254 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=254 ctermbg=NONE cterm=NONE
  hi String ctermfg=151 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=254 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=254 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=222 ctermbg=NONE cterm=NONE
  hi Type ctermfg=254 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=254 ctermbg=NONE cterm=NONE
  hi! link CursorLineNr LineNr
  hi! link diffAdded DiffAdd
  hi! link diffChanged DiffChange
  hi! link diffRemoved DiffDelete
  hi! link lCursor Cursor
  hi! link Macro Define
  hi! link Precondit PreProc
  hi! link WildMenu PmenuSel
  hi! link htmlEndTag htmlTag
  hi! link htmlItalic htmlItalic
  hi! link htmlH1 markdownH1
  hi! link htmlH2 markdownH1
  hi! link htmlH3 markdownH1
  hi! link htmlH4 markdownH1
  hi! link htmlH5 markdownH1
  hi! link htmlH6 markdownH1
  hi! link htmlSpecialChar SpecialChar
  hi! link htmlTag Keyword
  hi! link htmlTagN htmlTag
  hi! link jsBrackets Delimiter
  hi! link jsFuncCall Function
  hi! link jsFuncParens Delimiter
  hi! link jsThis Keyword
  hi! link jsPrototype Keyword
  hi! link jsRegexpString SpecialChar
  hi! link jsObjectKey jsonKeyword
  hi markdownH1 ctermfg=254 ctermbg=NONE cterm=bold
  hi! link markdownBold Bold
  hi! link markdownBoldDelimiter Keyword
  hi! link markdownFootnoteDefinition markdownFootnote
  hi! link markdownH2 markdownH1
  hi! link markdownH3 markdownH1
  hi! link markdownH4 markdownH1
  hi! link markdownH5 markdownH1
  hi! link markdownH6 markdownH1
  hi! link markdownIdDelimiter Keyword
  hi! link markdownItalic Italic
  hi! link markdownItalicDelimiter Keyword
  hi! link markdownLinkDelimiter Keyword
  hi! link markdownLinkTextDelimiter Keyword
  hi! link markdownListMarker Keyword
  hi! link markdownRule Keyword
  hi! link markdownHeadingDelimiter Keyword
  hi! link sassAmpersand Keyword
  hi! link sassControl Keyword
  hi! link sassControlLine Keyword
  hi! link sassExtend Keyword
  hi! link sassFor Keyword
  hi! link sassFunctionDecl Keyword
  hi! link sassReturn Keyword
  hi! link vimFunc Function
  hi! link vimFunction Function
  hi! link vimUserFunc Function
  hi! link yamlBool Keyword
  hi! link yamlDocumentStart Keyword
  hi ALEError ctermfg=131 ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=131 ctermbg=NONE cterm=NONE
  hi ALEWarning ctermfg=222 ctermbg=NONE cterm=underline
  hi ALEWarningSign ctermfg=222 ctermbg=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Keyword
  hi! link NERDTreeHelp Comment
  hi plugDeleted ctermfg=131 ctermbg=NONE cterm=NONE
  hi QuickScopePrimary ctermfg=131 ctermbg=NONE cterm=bold,underline
  hi QuickScopeSecondary ctermfg=131 ctermbg=NONE cterm=bold
  if !s:italics
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi TermCursorNC ctermfg=NONE ctermbg=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                 #3b4252               ~
" Color: red                   #bf616a               ~
" Color: green                 #a3be8c               ~
" Color: yellow                #ebcb8b               ~
" Color: blue                  #81a1c1               ~
" Color: magenta               #b48ead               ~
" Color: cyan                  #88c0d0               ~
" Color: white                 #e5e9f0               ~
" Color: accent                #c3d5b4               ~
" Color: light                 #e5e9f0               ~
" Color: dark                  #242932               ~
" Color: gray0                 #616e88               ~
" Color: gray1                 #4c566a               ~
" Color: gray2                 #363d4a               ~
" Color: gray3                 #131520               ~
" Term colors: black red green yellow blue magenta cyan white
" Term colors: gray1 red green yellow blue magenta cyan white
" vim: et ts=2 sw=2
