" Name:         Nordish
" Description:  Dark colorscheme heavily based on Nord
" Author:       Brandon Iffert <brandoniffert@gmail.com>
" Maintainer:   Brandon Iffert <brandoniffert@gmail.com>
" Website:      https://brandoniffert.com
" License:      Public domain
" Last Updated: Tue Mar 17 06:28:43 2020

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'nordish'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#3b4252', '#bf616a', '#a3be8c', '#ebcb8b',
        \ '#81a1c1', '#b48ead', '#88c0d0', '#e5e9f0', '#434c5e', '#bf616a',
        \ '#a3be8c', '#ebcb8b', '#81a1c1', '#b48ead', '#88c0d0', '#e5e9f0']
  if has('nvim')
    let g:terminal_color_0 = '#3b4252'
    let g:terminal_color_1 = '#bf616a'
    let g:terminal_color_2 = '#a3be8c'
    let g:terminal_color_3 = '#ebcb8b'
    let g:terminal_color_4 = '#81a1c1'
    let g:terminal_color_5 = '#b48ead'
    let g:terminal_color_6 = '#88c0d0'
    let g:terminal_color_7 = '#e5e9f0'
    let g:terminal_color_8 = '#434c5e'
    let g:terminal_color_9 = '#bf616a'
    let g:terminal_color_10 = '#a3be8c'
    let g:terminal_color_11 = '#ebcb8b'
    let g:terminal_color_12 = '#81a1c1'
    let g:terminal_color_13 = '#b48ead'
    let g:terminal_color_14 = '#88c0d0'
    let g:terminal_color_15 = '#e5e9f0'
  endif
  hi ColorColumn guifg=fg guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#3b4252 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=fg guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#131520 guibg=#a3be8c guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#131520 guibg=#ebcb8b guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#131520 guibg=#bf616a guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#131520 guibg=#81a1c1 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#3b4252 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#bf616a guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#bf616a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#434c5e guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=italic cterm=italic
  hi iCursor guifg=#3b4252 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#3b4252 guibg=#ebcb8b guisp=NONE gui=bold cterm=bold
  hi LineNr guifg=#2e3440 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#e5e9f0 guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#4c566a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#e5e9f0 guibg=#1e2229 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#3b4252 guibg=#e5e9f0 guisp=NONE gui=bold cterm=bold
  hi PmenuThumb guifg=#88c0d0 guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#bf616a guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi SignColumn guifg=#3b4252 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#434c5e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#bf616a guibg=#3b4252 guisp=NONE gui=underline cterm=underline
  hi SpellCap guifg=#ebcb8b guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi SpellLocal guifg=#e5e9f0 guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi SpellRare guifg=#e5e9f0 guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#4c566a guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#434c5e guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#434c5e guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#e5e9f0 guibg=#131520 guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#131520 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#3b4252 guibg=#ebcb8b guisp=NONE gui=bold cterm=bold
  hi healthError guifg=#bf616a guibg=NONE guisp=NONE gui=bold cterm=bold
  hi healthSuccess guifg=#a3be8c guibg=NONE guisp=NONE gui=bold cterm=bold
  hi healthWarning guifg=#ebcb8b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Boolean guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#4c566a guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#b48ead guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#b48ead guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=#3b4252 guibg=#ebcb8b guisp=NONE gui=bold cterm=bold
  hi Repeat guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#88c0d0 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Statement guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#a3be8c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonItalicComment guifg=#4c566a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CursorLineNr LineNr
  hi! link diffAdded DiffAdd
  hi! link diffChanged DiffChange
  hi! link diffRemoved DiffDelete
  hi! link lCursor Cursor
  hi! link Macro Define
  hi! link Precondit PreProc
  hi! link WildMenu PmenuSel
  hi cssAttributeSelector guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssDefinition guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssIdentifier guifg=#88c0d0 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi cssStringQ guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssAttr Keyword
  hi! link cssBraces Delimiter
  hi! link cssClassName cssDefinition
  hi! link cssColor Number
  hi! link cssProp cssDefinition
  hi! link cssPseudoClass cssDefinition
  hi! link cssPseudoClassId cssPseudoClass
  hi! link cssVendor Keyword
  hi htmlArg guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlLink guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link htmlEndTag htmlTag
  hi! link htmlItalic htmlItalic
  hi! link htmlH1 markdownH1
  hi! link htmlH2 markdownH1
  hi! link htmlH3 markdownH1
  hi! link htmlH4 markdownH1
  hi! link htmlH5 markdownH1
  hi! link htmlH6 markdownH1
  hi! link htmlSpecialChar SpecialChar
  hi! link htmlTag Keyword
  hi! link htmlTagN htmlTag
  hi jsGlobalNodeObjects guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsonKeyword guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsBrackets Delimiter
  hi! link jsFuncCall Function
  hi! link jsFuncParens Delimiter
  hi! link jsThis Keyword
  hi! link jsNoise Delimiter
  hi! link jsPrototype Keyword
  hi! link jsRegexpString SpecialChar
  hi! link jsObjectKey jsonKeyword
  hi! link jsxCloseString htmlTag
  hi! link logBrackets NonItalicComment
  hi! link logLevelTrace NonItalicComment
  hi markdownBlockquote guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCodeDelimiter guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownFootnote guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownId guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownIdDeclaration guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownH1 guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownLinkText guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#e5e9f0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBold Bold
  hi! link markdownBoldDelimiter Keyword
  hi! link markdownFootnoteDefinition markdownFootnote
  hi! link markdownH2 markdownH1
  hi! link markdownH3 markdownH1
  hi! link markdownH4 markdownH1
  hi! link markdownH5 markdownH1
  hi! link markdownH6 markdownH1
  hi! link markdownIdDelimiter Keyword
  hi! link markdownItalic Italic
  hi! link markdownItalicDelimiter Keyword
  hi! link markdownLinkDelimiter Keyword
  hi! link markdownLinkTextDelimiter Keyword
  hi! link markdownListMarker Keyword
  hi! link markdownRule Keyword
  hi! link markdownHeadingDelimiter Keyword
  hi sassClass guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassId guifg=#88c0d0 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi! link sassAmpersand Keyword
  hi! link sassClassChar Delimiter
  hi! link sassControl Keyword
  hi! link sassControlLine Keyword
  hi! link sassExtend Keyword
  hi! link sassFor Keyword
  hi! link sassFunctionDecl Keyword
  hi! link sassFunctionName Function
  hi! link sassidChar sassId
  hi! link sassInclude SpecialChar
  hi! link sassMixinName Function
  hi! link sassMixin SpecialChar
  hi! link sassReturn Keyword
  hi vimAugroup guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimMapRhs guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi vimNotation guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link vimFunc Function
  hi! link vimFunction Function
  hi! link vimUserFunc Function
  hi yamlBlockMappingKey guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi yamlKey guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link yamlBool Keyword
  hi! link yamlDocumentStart Keyword
  hi ALEError guifg=#bf616a guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEErrorSign guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=#ebcb8b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ALEWarningSign guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocErrorSign guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocHintSign guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocInfoSign guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi CocWarningSign guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LSPDiagnosticsError guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LSPDiagnosticsHint guifg=#81a1c1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LSPDiagnosticsInformation guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LSPDiagnosticsWarning guifg=#ebcb8b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeExecFile guifg=#88c0d0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Keyword
  hi! link NERDTreeHelp Comment
  hi plugDeleted guifg=#bf616a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi QuickScopePrimary guifg=#bf616a guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi QuickScopeSecondary guifg=#bf616a guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi TermCursor guifg=#3b4252 guibg=#e5e9f0 guisp=NONE gui=NONE cterm=NONE
    hi TermCursorNC guifg=NONE guibg=#3b4252 guisp=NONE gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi ColorColumn ctermfg=fg ctermbg=236 cterm=NONE
  hi Cursor ctermfg=238 ctermbg=254 cterm=NONE
  hi CursorColumn ctermfg=fg ctermbg=238 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
  hi DiffAdd ctermfg=233 ctermbg=108 cterm=NONE
  hi DiffChange ctermfg=233 ctermbg=222 cterm=NONE
  hi DiffDelete ctermfg=233 ctermbg=131 cterm=NONE
  hi DiffText ctermfg=233 ctermbg=110 cterm=NONE
  hi Directory ctermfg=109 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=NONE cterm=NONE
  hi Error ctermfg=131 ctermbg=238 cterm=NONE
  hi ErrorMsg ctermfg=131 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=239 ctermbg=233 cterm=NONE
  hi Folded ctermfg=254 ctermbg=233 cterm=italic
  hi iCursor ctermfg=238 ctermbg=254 cterm=NONE
  hi IncSearch ctermfg=238 ctermbg=222 cterm=bold
  hi LineNr ctermfg=236 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=254 ctermbg=238 cterm=NONE
  hi ModeMsg ctermfg=254 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=254 ctermbg=NONE cterm=NONE
  hi Normal ctermfg=254 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=240 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=254 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=254 ctermbg=233 cterm=NONE
  hi PmenuSel ctermfg=238 ctermbg=254 cterm=bold
  hi PmenuThumb ctermfg=109 ctermbg=239 cterm=NONE
  hi Question ctermfg=254 ctermbg=NONE cterm=NONE
  hi Search ctermfg=131 ctermbg=NONE cterm=bold,underline
  hi SignColumn ctermfg=238 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=239 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=131 ctermbg=238 cterm=underline
  hi SpellCap ctermfg=222 ctermbg=238 cterm=NONE
  hi SpellLocal ctermfg=254 ctermbg=238 cterm=NONE
  hi SpellRare ctermfg=254 ctermbg=238 cterm=NONE
  hi StatusLine ctermfg=240 ctermbg=233 cterm=NONE
  hi StatusLineNC ctermfg=239 ctermbg=233 cterm=NONE
  hi TabLine ctermfg=239 ctermbg=233 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=233 cterm=NONE
  hi TabLineSel ctermfg=254 ctermbg=233 cterm=NONE
  hi Terminal ctermfg=254 ctermbg=NONE cterm=NONE
  hi Title ctermfg=254 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=233 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=236 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
  hi WarningMsg ctermfg=238 ctermbg=222 cterm=bold
  hi healthError ctermfg=131 ctermbg=NONE cterm=bold
  hi healthSuccess ctermfg=108 ctermbg=NONE cterm=bold
  hi healthWarning ctermfg=222 ctermbg=NONE cterm=bold
  hi Boolean ctermfg=110 ctermbg=NONE cterm=NONE
  hi Character ctermfg=108 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=240 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=110 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=254 ctermbg=NONE cterm=NONE
  hi Define ctermfg=110 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=254 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=110 ctermbg=NONE cterm=NONE
  hi Float ctermfg=139 ctermbg=NONE cterm=NONE
  hi Function ctermfg=109 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=254 ctermbg=NONE cterm=NONE
  hi Include ctermfg=110 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=110 ctermbg=NONE cterm=NONE
  hi Label ctermfg=110 ctermbg=NONE cterm=NONE
  hi Number ctermfg=139 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=110 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=110 ctermbg=NONE cterm=NONE
  hi QuickFixLine ctermfg=238 ctermbg=222 cterm=bold
  hi Repeat ctermfg=110 ctermbg=NONE cterm=NONE
  hi Special ctermfg=254 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=222 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=109 ctermbg=NONE cterm=italic
  hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=110 ctermbg=NONE cterm=NONE
  hi String ctermfg=108 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=110 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=254 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=222 ctermbg=NONE cterm=NONE
  hi Type ctermfg=110 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=110 ctermbg=NONE cterm=NONE
  hi NonItalicComment ctermfg=240 ctermbg=NONE cterm=NONE
  hi! link CursorLineNr LineNr
  hi! link diffAdded DiffAdd
  hi! link diffChanged DiffChange
  hi! link diffRemoved DiffDelete
  hi! link lCursor Cursor
  hi! link Macro Define
  hi! link Precondit PreProc
  hi! link WildMenu PmenuSel
  hi cssAttributeSelector ctermfg=109 ctermbg=NONE cterm=NONE
  hi cssDefinition ctermfg=109 ctermbg=NONE cterm=NONE
  hi cssIdentifier ctermfg=109 ctermbg=NONE cterm=underline
  hi cssStringQ ctermfg=109 ctermbg=NONE cterm=NONE
  hi! link cssAttr Keyword
  hi! link cssBraces Delimiter
  hi! link cssClassName cssDefinition
  hi! link cssColor Number
  hi! link cssProp cssDefinition
  hi! link cssPseudoClass cssDefinition
  hi! link cssPseudoClassId cssPseudoClass
  hi! link cssVendor Keyword
  hi htmlArg ctermfg=109 ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=254 ctermbg=NONE cterm=NONE
  hi! link htmlEndTag htmlTag
  hi! link htmlItalic htmlItalic
  hi! link htmlH1 markdownH1
  hi! link htmlH2 markdownH1
  hi! link htmlH3 markdownH1
  hi! link htmlH4 markdownH1
  hi! link htmlH5 markdownH1
  hi! link htmlH6 markdownH1
  hi! link htmlSpecialChar SpecialChar
  hi! link htmlTag Keyword
  hi! link htmlTagN htmlTag
  hi jsGlobalNodeObjects ctermfg=109 ctermbg=NONE cterm=NONE
  hi jsonKeyword ctermfg=109 ctermbg=NONE cterm=NONE
  hi! link jsBrackets Delimiter
  hi! link jsFuncCall Function
  hi! link jsFuncParens Delimiter
  hi! link jsThis Keyword
  hi! link jsNoise Delimiter
  hi! link jsPrototype Keyword
  hi! link jsRegexpString SpecialChar
  hi! link jsObjectKey jsonKeyword
  hi! link jsxCloseString htmlTag
  hi! link logBrackets NonItalicComment
  hi! link logLevelTrace NonItalicComment
  hi markdownBlockquote ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownCodeDelimiter ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownFootnote ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownH1 ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownLinkText ctermfg=109 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=254 ctermbg=NONE cterm=NONE
  hi! link markdownBold Bold
  hi! link markdownBoldDelimiter Keyword
  hi! link markdownFootnoteDefinition markdownFootnote
  hi! link markdownH2 markdownH1
  hi! link markdownH3 markdownH1
  hi! link markdownH4 markdownH1
  hi! link markdownH5 markdownH1
  hi! link markdownH6 markdownH1
  hi! link markdownIdDelimiter Keyword
  hi! link markdownItalic Italic
  hi! link markdownItalicDelimiter Keyword
  hi! link markdownLinkDelimiter Keyword
  hi! link markdownLinkTextDelimiter Keyword
  hi! link markdownListMarker Keyword
  hi! link markdownRule Keyword
  hi! link markdownHeadingDelimiter Keyword
  hi sassClass ctermfg=109 ctermbg=NONE cterm=NONE
  hi sassId ctermfg=109 ctermbg=NONE cterm=underline
  hi! link sassAmpersand Keyword
  hi! link sassClassChar Delimiter
  hi! link sassControl Keyword
  hi! link sassControlLine Keyword
  hi! link sassExtend Keyword
  hi! link sassFor Keyword
  hi! link sassFunctionDecl Keyword
  hi! link sassFunctionName Function
  hi! link sassidChar sassId
  hi! link sassInclude SpecialChar
  hi! link sassMixinName Function
  hi! link sassMixin SpecialChar
  hi! link sassReturn Keyword
  hi vimAugroup ctermfg=109 ctermbg=NONE cterm=NONE
  hi vimMapRhs ctermfg=109 ctermbg=NONE cterm=NONE
  hi vimNotation ctermfg=109 ctermbg=NONE cterm=NONE
  hi! link vimFunc Function
  hi! link vimFunction Function
  hi! link vimUserFunc Function
  hi yamlBlockMappingKey ctermfg=109 ctermbg=NONE cterm=NONE
  hi yamlKey ctermfg=109 ctermbg=NONE cterm=NONE
  hi! link yamlBool Keyword
  hi! link yamlDocumentStart Keyword
  hi ALEError ctermfg=131 ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=131 ctermbg=NONE cterm=NONE
  hi ALEWarning ctermfg=222 ctermbg=NONE cterm=underline
  hi ALEWarningSign ctermfg=222 ctermbg=NONE cterm=NONE
  hi CocErrorSign ctermfg=131 ctermbg=NONE cterm=NONE
  hi CocHintSign ctermfg=110 ctermbg=NONE cterm=NONE
  hi CocInfoSign ctermfg=109 ctermbg=NONE cterm=NONE
  hi CocWarningSign ctermfg=222 ctermbg=NONE cterm=NONE
  hi LSPDiagnosticsError ctermfg=131 ctermbg=NONE cterm=NONE
  hi LSPDiagnosticsHint ctermfg=110 ctermbg=NONE cterm=NONE
  hi LSPDiagnosticsInformation ctermfg=109 ctermbg=NONE cterm=NONE
  hi LSPDiagnosticsWarning ctermfg=222 ctermbg=NONE cterm=NONE
  hi NERDTreeExecFile ctermfg=109 ctermbg=NONE cterm=NONE
  hi! link NERDTreeCWD Comment
  hi! link NERDTreeDirSlash Keyword
  hi! link NERDTreeHelp Comment
  hi plugDeleted ctermfg=131 ctermbg=NONE cterm=NONE
  hi QuickScopePrimary ctermfg=131 ctermbg=NONE cterm=bold,underline
  hi QuickScopeSecondary ctermfg=131 ctermbg=NONE cterm=bold
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  if has('nvim')
    hi TermCursor ctermfg=238 ctermbg=254 cterm=NONE
    hi TermCursorNC ctermfg=NONE ctermbg=238 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                 #3b4252               ~
" Color: red                   #bf616a               ~
" Color: green                 #a3be8c               ~
" Color: yellow                #ebcb8b               ~
" Color: blue                  #81a1c1               ~
" Color: magenta               #b48ead               ~
" Color: cyan                  #88c0d0               ~
" Color: white                 #e5e9f0               ~
" Color: gray0                 #131520               ~
" Color: gray1                 #1e2229               ~
" Color: gray2                 #2e3440               ~
" Color: gray3                 #434c5e               ~
" Color: gray4                 #4c566a               ~
" Term colors: black red green yellow blue magenta cyan white
" Term colors: gray3 red green yellow blue magenta cyan white
" vim: et ts=2 sw=2
