#!/bin/bash

set -euo pipefail

if ! /usr/bin/xcode-select --print-path &>/dev/null; then
  echo
  echo 'Installing XCode Command Line Tools...'
  echo

  # Prompt to install the XCode Command Line Tools
  /usr/bin/xcode-select --install &>/dev/null

  # Wait until the XCode Command Line Tools are installed
  until xcode-select --print-path &>/dev/null; do
    sleep 5
  done
fi

read -r -p "Do you want to clone the repo to the current directory? [y|N] " response
if [[ $response =~ (yes|y|Y) ]]; then
  command git clone --recurse-submodules https://github.com/brandoniffert/computer.git
  echo
  echo '=> Cloned repo! cd into the directory and run ./scripts/install'
  echo
else
  echo
  echo 'Exiting...'
  echo
  exit 0
fi
